export default {
	CREATE_PASSWORD: '/create-password',
	CREATE_PASSWORD_SUCCESS: '/create-password-success',
	CREATE_PASSWORD_ERROR: '/create-password-error',
	RESET_PASSWORD: '/reset-password',
	FORGOT_PASSWORD: '/forgot-password',
	FORGOT_PASSWORD_SUCCESS: '/forgot-password-success',
	FORGOT_PASSWORD_ERROR: '/forgot-password-error',
	RESET_PASSWORD_SUCCESS: '/reset-password-success',
	RESET_PASSWORD_ERROR: '/reset-password-error',
	INBOX: '/inbox',
	SCENARIOS: '/scenarios',
	SCENARIOS_NEW: '/scenarios/new',
	SIGN_IN: '/signin',
	TEAM: '/groups',
	TEAM_NEW: '/groups/new',
	PROFILE: '/profile',
	SETTINGS: '/settings',
};
