export default {
	USER__FORGOT_PASSWORD__REQUEST_ERROR: 'USER__FORGOT_PASSWORD__REQUEST_ERROR',
	USER__FORGOT_PASSWORD__REQUEST_SUCCESS: 'USER__FORGOT_PASSWORD__REQUEST_SUCCESS',
	USER__FORGOT_PASSWORD__REQUEST: 'USER__FORGOT_PASSWORD__REQUEST',
	USER__GET_INFO__REQUEST_ERROR: 'USER__GET_INFO__REQUEST_ERROR',
	USER__GET_INFO__REQUEST_SUCCESS: 'USER__GET_INFO__REQUEST_SUCCESS',
	USER__GET_INFO__REQUEST: 'USER__GET_INFO__REQUEST',
	USER__RESET_PASSWORD__REQUEST: 'USER__RESET_PASSWORD__REQUEST',
	USER__SIGN_IN__REQUEST_ERROR: 'USER__SIGN_IN__REQUEST_ERROR',
	USER__SIGN_IN__REQUEST_SUCCESS: 'USER__SIGN_IN__REQUEST_SUCCESS',
	USER__SIGN_IN__REQUEST: 'USER__SIGN_IN__REQUEST',
	USER__SIGN_OUT: 'USER__SIGN_OUT',
};
